from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(976, 729)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 951, 641))
        self.tabWidget.setMinimumSize(QtCore.QSize(951, 641))
        self.tabWidget.setMaximumSize(QtCore.QSize(951, 641))
        self.tabWidget.setSizeIncrement(QtCore.QSize(20, 20))
        self.tabWidget.setBaseSize(QtCore.QSize(10, 10))
        self.tabWidget.setStyleSheet("font: 75 12pt \"Verdana\";")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(20, 10, 111, 31))
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(self.tab)
        self.textEdit.setGeometry(QtCore.QRect(140, 10, 731, 41))
        self.textEdit.setObjectName("textEdit")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 101, 31))
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(self.tab)
        self.comboBox.setGeometry(QtCore.QRect(140, 90, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.comboBox.setFont(font)
        self.comboBox.setEditable(True)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setItemText(5, "")
        self.horizontalSlider = QtWidgets.QSlider(self.tab)
        self.horizontalSlider.setGeometry(QtCore.QRect(140, 140, 241, 16))
        self.horizontalSlider.setMaximum(100)
        self.horizontalSlider.setSliderPosition(80)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.scrollArea = QtWidgets.QScrollArea(self.tab)
        self.scrollArea.setGeometry(QtCore.QRect(610, 120, 191, 451))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 189, 449))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(430, 60, 381, 71))
        self.label_3.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab)
        self.comboBox_2.setGeometry(QtCore.QRect(140, 210, 211, 51))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(20, 210, 91, 51))
        self.label_4.setObjectName("label_4")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(20, 300, 311, 121))
        self.label_8.setObjectName("label_8")
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_2.setGeometry(QtCore.QRect(340, 340, 51, 41))
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_28 = QtWidgets.QLabel(self.tab)
        self.label_28.setGeometry(QtCore.QRect(400, 120, 71, 51))
        self.label_28.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";")
        self.label_28.setObjectName("label_28")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(40, 10, 141, 51))
        self.label_5.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(30, 170, 141, 51))
        self.label_6.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(30, 330, 141, 51))
        self.label_7.setObjectName("label_7")
        self.listView = QtWidgets.QListView(self.tab_2)
        self.listView.setGeometry(QtCore.QRect(40, 50, 201, 111))
        self.listView.setObjectName("listView")
        self.listView_2 = QtWidgets.QListView(self.tab_2)
        self.listView_2.setGeometry(QtCore.QRect(30, 210, 201, 111))
        self.listView_2.setObjectName("listView_2")
        self.listView_3 = QtWidgets.QListView(self.tab_2)
        self.listView_3.setGeometry(QtCore.QRect(30, 370, 201, 251))
        self.listView_3.setObjectName("listView_3")
        self.listView1 = QtWidgets.QListView(self.tab_2)
        self.listView1.setGeometry(QtCore.QRect(280, 40, 621, 291))
        self.listView1.setObjectName("listView1")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(160, 160, 111, 31))
        self.label_9.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setGeometry(QtCore.QRect(150, 320, 111, 31))
        self.label_10.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setGeometry(QtCore.QRect(390, 10, 281, 31))
        self.label_11.setObjectName("label_11")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.tab_2)
        self.plainTextEdit.setGeometry(QtCore.QRect(280, 330, 621, 241))
        self.plainTextEdit.setStyleSheet("background-color: rgb(174, 255, 152);")
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.pushButton = QtWidgets.QPushButton(self.tab_2)
        self.pushButton.setGeometry(QtCore.QRect(660, 580, 121, 41))
        self.pushButton.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.pushButton.setObjectName("pushButton")
        self.label_27 = QtWidgets.QLabel(self.tab_2)
        self.label_27.setGeometry(QtCore.QRect(800, 580, 51, 41))
        self.label_27.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";")
        self.label_27.setObjectName("label_27")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_23 = QtWidgets.QLabel(self.tab_3)
        self.label_23.setGeometry(QtCore.QRect(20, 400, 141, 51))
        self.label_23.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";")
        self.label_23.setObjectName("label_23")
        self.listView_8 = QtWidgets.QListView(self.tab_3)
        self.listView_8.setGeometry(QtCore.QRect(20, 440, 201, 111))
        self.listView_8.setObjectName("listView_8")
        self.label_24 = QtWidgets.QLabel(self.tab_3)
        self.label_24.setGeometry(QtCore.QRect(140, 550, 111, 31))
        self.label_24.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_24.setObjectName("label_24")
        self.groupBox = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox.setGeometry(QtCore.QRect(250, 420, 321, 121))
        self.groupBox.setObjectName("groupBox")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setGeometry(QtCore.QRect(10, 40, 261, 31))
        self.radioButton.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(10, 70, 391, 41))
        self.radioButton_2.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.tab_3)
        self.radioButton_3.setGeometry(QtCore.QRect(260, 560, 281, 31))
        self.radioButton_3.setObjectName("radioButton_3")
        self.label_25 = QtWidgets.QLabel(self.tab_3)
        self.label_25.setGeometry(QtCore.QRect(620, 0, 201, 81))
        self.label_25.setObjectName("label_25")
        self.listView_9 = QtWidgets.QListView(self.tab_3)
        self.listView_9.setGeometry(QtCore.QRect(620, 70, 256, 541))
        self.listView_9.setObjectName("listView_9")
        self.widget = QtWidgets.QWidget(self.tab_3)
        self.widget.setGeometry(QtCore.QRect(40, 40, 531, 321))
        self.widget.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.widget.setObjectName("widget")
        self.label_26 = QtWidgets.QLabel(self.tab_3)
        self.label_26.setGeometry(QtCore.QRect(40, 10, 161, 21))
        self.label_26.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";")
        self.label_26.setObjectName("label_26")
        self.tabWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 976, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.horizontalSlider.sliderMoved['int'].connect(self.label_28.setNum)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Query/IPC"))
        self.label_2.setText(_translate("MainWindow", "Criterion"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Insert the criterion"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Technology"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Material"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Type"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Application/Use"))
        self.label_3.setText(_translate("MainWindow", "Clustering would be based on the following terms:"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "k-means extended"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "c-means extended"))
        self.label_4.setText(_translate("MainWindow", "Model"))
        self.label_8.setText(_translate("MainWindow", "Number of classes (Optional)"))
        self.label_28.setText(_translate("MainWindow", "80"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Preprocessing"))
        self.label_5.setText(_translate("MainWindow", "Top 5 classes"))
        self.label_6.setText(_translate("MainWindow", "Top 5 authors"))
        self.label_7.setText(_translate("MainWindow", "Key terms"))
        self.label_9.setText(_translate("MainWindow", "show more"))
        self.label_10.setText(_translate("MainWindow", "show more"))
        self.label_11.setText(_translate("MainWindow", "Class: [name of the class]"))
        self.pushButton.setText(_translate("MainWindow", "Update Classes"))
        self.label_27.setText(_translate("MainWindow", "Trial: "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Classes"))
        self.label_23.setText(_translate("MainWindow", "Top 5 classes"))
        self.label_24.setText(_translate("MainWindow", "show more"))
        self.groupBox.setTitle(_translate("MainWindow", "Trends"))
        self.radioButton.setText(_translate("MainWindow", " Uptrends (increasing)"))
        self.radioButton_2.setText(_translate("MainWindow", " Disciplinary trends (co-occurrences)"))
        self.radioButton_3.setText(_translate("MainWindow", " Stable technologies"))
        self.label_25.setText(_translate("MainWindow", "List of technologies"))
        self.label_26.setText(_translate("MainWindow", "Time series visualization"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Trends"))

#import icon_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

